# Verbindung zur PostgreSQL-Datenbank in Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/disysuser
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

# Automatische Erstellung der Tabellen aktivieren
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Verbindung zu RabbitMQ in Docker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest